-- MySQL Script generated by MySQL Workbench
-- Fri May 27 09:56:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema LOCATION DE FILM
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema LOCATION DE FILM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LOCATION DE FILM` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `LOCATION DE FILM` ;

-- -----------------------------------------------------
-- Table `LOCATION DE FILM`.`Catégorie de films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCATION DE FILM`.`Catégorie de films` (
  `IdCatégorie` INT NOT NULL AUTO_INCREMENT,
  `Comédie` VARCHAR(45) NOT NULL,
  `Action` VARCHAR(45) NOT NULL,
  `Drame` VARCHAR(45) NOT NULL,
  `Horreur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdCatégorie`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LOCATION DE FILM`.`Info Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCATION DE FILM`.`Info Clients` (
  `idInfo clients` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prénoms` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idInfo clients`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LOCATION DE FILM`.`Info films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCATION DE FILM`.`Info films` (
  `IdInfo films` INT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(45) NOT NULL,
  `Date de sortie` VARCHAR(45) NOT NULL,
  `Durée` VARCHAR(45) NOT NULL,
  `Réalisateur` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdInfo films`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `LOCATION DE FILM`.`Payement clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCATION DE FILM`.`Payement clients` (
  `IdPayement` INT NOT NULL AUTO_INCREMENT,
  `Date de payement` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Montant` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdPayement`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
